config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do

  namespace :api, defaults: {format: 'json'}, :path => '', constraints: {subdomain: 'api'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :events
      resources :users, only: [:index, :show]
      resources :relationships, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :attends, only: [:create, :destroy]
      devise_scope :user do
        match '/login' => 'sessions#create', :via => :post
        match '/logout' => 'sessions#destroy', :via => :delete
        match '/sign_up' => 'registrations#create', :via => :post
      end
    end
  end

  get 'main_pages/index'

  root to: 'prelaunch#index'

  match 'about', to: 'main_pages#about', via: 'get'

  match 'admin', to: 'admin_panel#index', via: 'get'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

	resources :users, only: [:index, :show] do
		member do
			get :followings, :followers
		end
	end

  resources :events

  resources :tickets, :ticket_types, :categories, :cities, :states, :purchases

	resources :relationships, only: [:create, :destroy]

  resources :likes, only: [:create, :destroy]

  resources :attends, only: [:create, :destroy]

end

app/models/event.rb
class Event < ActiveRecord::Base
	dragonfly_accessor :flyer

	# Database Relationships
	belongs_to :user
	belongs_to :state
	belongs_to :city
	belongs_to :category
	has_many :ticket_types
	has_many :tickets, through: :ticket_types

	has_many :reverse_likes, foreign_key: "liked_id", class_name: "Like", dependent: :destroy
	has_many :likers, through: :reverse_likes, source: :liker

	has_many :reverse_attends, foreign_key: "attended_id", class_name: "Attend", dependent: :destroy
	has_many :attendees, through: :reverse_attends, source: :attendee

	accepts_nested_attributes_for :ticket_types, allow_destroy: true


	# Validations
	validates_presence_of :title, :location_name, :details, :category_id, :state, :city_id
	validates :title, length: {maximum: 50}
	validates :street, length: {maximum: 500}, allow_nil: true
	validates :zip, length: {is: 5}
	validates :youtube_id, length: {maximum: 100}, allow_nil: true

	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	# Methods
	def address
		if street.present?
			"#{street} #{city.name}, #{state.name} #{zip}"
		else
			"#{city.name}, #{state.name} #{zip}"
		end
	end

	def address_changed?
		attrs = %w(street city_id state_id zip)
		attrs.any?{|a| send "#{a}_changed?"}
	end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < EventsController
  #before_filter :authenticate_user!, except: [:show]
  respond_to :json

  def index
    if params[:search].present?
      respond_with @events = Event.near(params[:search], 25)
    else
      respond_with @events = Event.all
    end
  end

  def show
    @event = Event.find(params[:id])
    respond_with @event
  end

  def new
    respond_with @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = 'Event created'
      redirect_to user_url(current_user)
    else
      render 'new'
    end
    respond_with @event
  end

  def edit
    respond_with @event = current_user.events.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      flash[:success] = 'Event updated'
      redirect_to event_url
    else
      render 'edit'
    end
    respond_with @event
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_with @event
    redirect_to current_user
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	#before_action :authenticate_user!, except: :show
	def index
		if params[:search].present?
			@events = Event.near(params[:search], 25)
		else
			@events = Event.all
		end
	end

	def show
		@event = Event.find(params[:id])
		@attendees = @event.attendees
		@body_id = 'show_body'
	end

	def new
		@event = current_user.events.build
		1.times { @event.ticket_types.build }
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			flash[:success] = 'Event created'
			redirect_to user_url(current_user)
		else
			render 'new'
		end
	end

	def edit
		@event = current_user.events.find(params[:id])
	end

	def update
		@event = current_user.events.find(params[:id])
		if @event.update(event_params)
			flash[:success] = 'Event updated'
			redirect_to event_url
		else
			render 'edit'
		end
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to current_user
	end

	private

	def event_params
		params.require(:event).permit(:title, :location_name, :street, :city_id,
		                              :state_id, :zip, :start, :end, :details,
		                              :category_id, :youtube_id, :flyer,
		                              :longitude, :latitude,
		                              :ticket_types_attributes => [:id, :name, :description, :cost, :quantity, :_destroy])
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<%= form_for(current_user.attends.build(attended_id: @event.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :attended_id %></div>
  <%= f.submit "Attend", class: "btn btn-default" %>
<% end %>

app/views/events/_attend_form.html.erb
<div id="attend_form">
  <% if current_user.attending?(@event) %>
    <%= render 'leave' %>
  <% else %>
    <%= render 'attend' %>
  <% end %>
</div>

app/views/events/_form.html.erb
<div class="event-form">
  <%= form_for(@event, html: {class: 'form-horizontal col-sm-8'}) do |f| %>
    <div class="event-form-table">
      <div class="form-group"><%= f.label :title, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"> <%= f.text_field :title, maxlength: 80, placholder: 'Give your event a title', class: 'form-control' %></div>
      </div>
      <div class="form-group"><%= f.label :flyer, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10"><%= f.file_field :flyer, class: 'form-control' %></div>
      </div>

      <div class="form-group"><%= f.label 'Location', class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.text_field :location_name, placeholder: 'Name of venue', class: 'form-control' %></div>
      </div>

      <div class="form-group"><%= f.label :street, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.text_field :street, placeholder: 'Address line', class: 'form-control' %></div>
      </div>

      <div class="form-group"><%= f.label :state, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.collection_select(:state_id, State.order(:name), :id, :name,
                                                       {prompt: 'Select a state or province'},
                                                       {class: 'form-control'}) %></div>
      </div>

      <div class="form-group"><%= f.label :city, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.grouped_collection_select(:city_id, State.order(:name), :cities, :name, :id, :name,
                                                               {prompt: 'Select a city'},
                                                               {class: 'form-control'}) %></div>
      </div>

      <div class="form-group"><%= f.label :zip, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.text_field :zip, maxlength: 5, placeholder: 'Zip', class: 'form-control' %></div>
      </div>

      <div class="form-group"><%= f.label :start, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.datetime_select(:start,
                                                     start_year: Date.today.year,
                                                     minute_step: 5,
                                                     ampm: true,
                                                     default: 1.days.from_now,
                                                     order: [:month, :day, :year]) %></div>
      </div>

      <div class="form-group"><%= f.label :end, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.datetime_select(:end,
                                                     start_year: Date.today.year,
                                                     minute_step: 5, ampm: true,
                                                     default: 1.days.from_now,
                                                     order: [:month, :day, :year]) %></div>
      </div>

      <div class="form-group"><%= f.label :category_id, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.collection_select(:category_id, Category.order(:name), :id, :name, {prompt: 'Select one'}, {class: 'form-control'}) %></div>
      </div>

      <div class="form-group"><%= f.label 'Youtube Video ID', class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.text_field :youtube_id, class: 'form-control' %></div>
      </div>

      <div class="form-group"><%= f.label :details, class: 'col-sm-2 control-label' %>

        <div class="col-sm-10"><%= f.text_area :details, rows: 15, placholder: 'Tell people aobut your event and what makes it special!', class: 'form-control' %></div>
      </div>
      <div>
        <hr>
        <h2>Tickets</h2>
        <hr>
        <%= f.fields_for :ticket_types do |builder| %>
          <%= render 'ticket_type_fields', f: builder %>
        <% end %>
        <%= link_to_add_fields " Add Ticket", f, :ticket_types %>
      </div>
    </div>
    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_leave.html.erb
<%= form_for(current_user.attends.find_by_attended_id(@event), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Attending", class: "btn btn-success" %>
<% end %>

app/views/events/_like.html.erb
<%= form_for(current_user.likes.build(liked_id: @event.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :liked_id %></div>
  <%= f.submit "Like", class: "btn btn-default" %>
<% end %>

app/views/events/_like_form.html.erb
  <div id="like_form">
    <% if current_user.liked?(@event) %>
      <%= render 'unlike' %>
    <% else %>
      <%= render 'like' %>
    <% end %>
  </div>

app/views/events/_ticket_type_fields.html.erb
<fieldset class="ticket-form">
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10"><%= f.text_field :name, placeholder: 'General Admission', class: 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label 'Details', class: 'control-label col-sm-2' %>
    <div class="col-sm-10"><%= f.text_area :description, rows: 3, placeholder: 'Add your details', class: 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label :cost, class: 'control-label col-sm-2' %>
    <div class="col-sm-10"><%= f.number_field :cost, placeholder: '15.00', class: 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: 'control-label col-sm-2' %>
    <div class="col-sm-10"><%= f.number_field :quantity, placeholder: '100', class: 'form-control' %></div>
  </div>
  <%= f.hidden_field :_destroy %>
  <%= link_to "", '#', class: 'remove_fields glyphicon glyphicon-trash' %>
</fieldset>

app/views/events/_ticket_types_fileds.html.erb
<fieldset>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'General Admission' %><br/>
  <%= f.label 'Details' %>
  <%= f.text_area :description, rows: 3, placeholder: 'Add your details' %><br/>
  <%= f.label :cost %>
  <%= f.number_field :cost, placeholder: '15.00' %><br/>
  <%= f.label :quantity %>
  <%= f.number_field :quantity, placeholder: '100' %><br/>
  <%= f.hidden_field :_destroy %>
  <%= f.check_box :_destroy %>
</fieldset>

app/views/events/_unlike.html.erb
<%= form_for(current_user.likes.find_by_liked_id(@event), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unlike", class: "btn btn-success" %>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <h1>Edit Event</h1>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="row event-search">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_tag events_path, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: 'form-control', placholder: 'Enter your city..' %>
        <span class="input-group-btn">
        <%= submit_tag 'Search Near', :name => nil, class: 'btn btn-success' %>
      </span>
      </div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>
<div class="page-header row">
  <% if params[:search].present? %>
    <h1 class="col-md-10"><%= params[:search].upcase %> Events </h1>
  <% else %>
    <h1 class="col-md-10">All Events</h1>
  <% end %>
  <span class="pull-right btn btn-default col-md-2"><%= link_to '+ Create Event', new_event_path %></span>
</div>

<div>
  <% @events.each do |event| %>
    <div class="event <%= "event-#{event.id}" %> col-md-4">
      <div class="event-info card">
        <div class="gradient">
          <div class="event-index-details">
            <h4><%= link_to event.title, event_path(event) %></h4>
            <span class="location"><%= event.location_name %></span><br>
            <span class="address"><%= "#{event.city.name}, #{event.state.name} #{event.zip}" %></span><br>
            <span class="time"><%= event.start.strftime('%a %b %d, %Y | %I:%M %p') %></span><br>
          </div>
        </div>
      </div>
    </div>
  <% end  %>
</div>

app/views/events/new.html.erb
<div class="page-header">
  <h1>Create Event</h1>
</div>
<%= render 'form' %>

app/views/events/show.html.erb
<% provide(:title, "#{@event.title}") %>
<div class="event col-sm-12">
  <div class="page-header">
    <h1><%= @event.title %></h1>
    <% if current_user == @event.user %>
      <span><%= link_to "", edit_event_path, class: 'glyphicon glyphicon-pencil' %></span>
    <span><%= link_to "", @event, class: 'glyphicon glyphicon-trash', method: :delete,
                      data: { confirm: "Are you sure you want to delet #{@event.title}?"}, title: @event.title %>
    </span>
    <% end %>
    <% if user_signed_in? %>
      <%= render 'events/like_form' %>
    <% end %>
  </div>
  <div class="event-flyer"></div>

  <div class="event-header">
    <div class="event-host">
      <h5>Host: <%= link_to "#{@event.user.username}", user_path(@event.user) %></h5>
    </div>
  </div>

  <div class="event-body">
    <div class="event-col-a col-md-8">
      <div class="event-summary">

        <div class="event-times">
          <table class="event-table">
            <tbody>
            <tr>
              <td class="event-lable">
                <b>Time:</b>
              </td>
              <td>
                <p><%= @event.start.strftime('%A %B %d, %Y | %I:%M %p') %></p>
                <p><%= @event.end.strftime('%A %B %d, %Y | %I:%M %p') %></p>
              </td>
            </tr>
            </tbody>
          </table>
        </div>

        <div class="event-address">
          <table class="event-table">
            <tbody>
            <tr>
              <td class="event-label">
                <b>Location</b>
              </td>
              <td>
                <p><%= @event.location_name %></p>
                <p><%= "#{@event.address}" %></p>
              </td>
            </tr>
            </tbody>
          </table>
        </div>

        <div class="event-category">
          <table class="event-table">
            <tbody>
            <tr>
              <td class="event-label">
                <b>Event Type</b>
              </td>
              <td>
                <p><%= @event.category.name %></p>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>

      <% if @event.youtube_id.present? %>
        <div class="event-video">
          <div class="video-container">
            <iframe width="778" height="438" src="//www.youtube.com/embed/<%= @event.youtube_id %>"
                    frameborder="0" allowfullscreen></iframe>
          </div>
        </div>
      <% end %>

      <% if @event.ticket_types.present? %>
        <div class="event-tickets">
          <table style="width: 100%;">
            <tr class="ticket-header">
              <td>Name</td>
              <td>Cost</td>
              <td>Fee</td>
              <td>Total Price</td>
              <td></td>
            </tr>
          <% @event.ticket_types.each do |ticket| %>
            <tr class="ticket-types">
              <td><%= ticket.name %></td>
              <td><%= number_to_currency(ticket.cost) %></td>
              <td><%= number_to_currency(ticket.ticket_fee) %></td>
              <td><%= number_to_currency(ticket.total_price) %></td>
              <td><button class="btn btn-success btn-xs">Get Now!</button> </td>
            </tr>
          <% end %>
          </table>
        </div>
      <%end %>
      <div class="event-details">
        <b>EVENT DETAILS</b>
        <%= simple_format(@event.details) %>
      </div>
    </div>
    <!-- Event Sidebar -->
    <div class="event-col-b col-md-4">
      <div class="event-guest">
        <% if user_signed_in? %>
          <%= render 'events/attend_form' %>
        <% end %>
        <% if user_signed_in? %>
          <h2>Guest</h2>
          <div id="attendees_count"><%= @event.attendees.count %></div>
          <ul id="attendees">
            <% @attendees.each do |attendee| %>
            <li><%= link_to attendee.username, attendee %></li>
            <% end %>
          </ul>
        <% else %>
          <h2>Guest</h2>
          <p>Find out who's going by singing in <%= link_to "here", new_user_session_path %></p>
        <% end %>
      </div>
      <div class="nearby">
        <h3>Nearby Events</h3>
        <ul>
          <% for event in @event.nearbys(10).limit(5) %>
            <li><%= link_to event.title, event %> (<%= event.distance.round(2) %> miles)</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>


</div>